version: 0.2

phases:
  install:
    commands:
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli

      # Install backend dependencies
      - cd ${CODEBUILD_SRC_DIR}/backend
      - npm install --quiet

      # Install frontend dependencies
      - cd ${CODEBUILD_SRC_DIR}/frontend
      - npm install --quiet
  pre_build:
    commands:
      # Discover and run unit tests
      #- npm run --prefix ./frontend test-ci
  build:
    commands:
      # Build frontend
      - npm run build
      
      # Upload frontend
      - aws s3 cp --recursive build s3://$WEBSITE_S3_BUCKET/public/ --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers
      #- sed -i -e "s|assets/|$WEBSITE_S3_PREFIX/public/assets/|g" public/index.html

      # Package cloudformation template
      - aws cloudformation package --debug --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
artifacts:
  type: zip
  files:
    - template-export.yml
